services:
  automation:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./reports:/usr/src/app/reports
      - ./.env:/usr/src/app/.env
    environment:
      - NODE_ENV=development
      - DISPLAY=${DISPLAY}
    env_file:
      - .env
    command: ["pnpm", "web"]
    networks:
      - automation-network

networks:
  automation-network:
    driver: bridge